### PR TITLE
Still a work in progress, but I want you to take notice for now

### PR DESCRIPTION
**Pull request by joemsak**
I implemented a rake task to find & store book titles in the db
So books link out to the ISBNdb, if they were found
Still working away at this, but want to share the love
I'm collaborating with "nicinabox" and if we win, I promise to split the lovebucks with him

Thanks, Cheers!

### CODE REVIEW

**Comment by wanderingmatt** [comment]
Huge fan of the search filter - wish I'd thought of that! Love the clean layout as well as the individual card views.

**Comment by joemsak** [comment]
Thanks man:) gotta give nicinabox the design credit, without him i'd be dead in the water

**Comment by goncalossilva** [comment]
This is one of my favorites. Very clean design. Minimalist interfaces <3

The search filter is awesome.

**Comment by nicinabox** [comment]
Thank you :D

<3mmlst

**Comment by ejc** [comment]
Big fan of this entry. Search filter, the look, simplicity.

Great work guys.

**Comment by joemsak** [comment]
Aw man, thanks! Your illustration skills are p. phenomenal!

**Comment by mnoble** [comment]
+1

I love this entry. It very much matches the idea of simplicity and elegance we're all used to with the language itself. Very nice work guys!

**Comment by joemsak** [comment]
Thank you!! :)

**Comment by turboladen** [comment]
Very clean.  Love the quote at the top.  Nice!

**Comment by nicinabox** [comment]
What's more Japanese than a haiku? :)

**Comment by maxim** [comment]
Good compromise between clean design and much info at fingertips. I would prefer to learn a little more from the homepage though.

**Pull request closed without merging**
