### PR TITLE
http://heroesofruby.heroku.com/ Fork

### PR DESCRIPTION
**Pull request by fredwu**
Live preview: http://heroesofruby.heroku.com/

**System Features**
- Lightweight system powered by Padrino
- SQLite3 instead of MySQL
- Slim instead of ERb
- Sass for CSS
- Local portrait images

**Presentation Features**
- Parallax header and footer
- 16x16px social network icons

**Content Features**
- Hero blurb (i.e. for team introduction)
- Committer bios in both English and Japanese

Website tested in IE7/IE8/FF3/FF4/Safari/Chrome.

:-)

### CODE REVIEW

**Comment by joho** [comment]
I like it except for the weird jittering shadows behind the people.

**Comment by jimmycuadra** [comment]
This is my favorite.

**Comment by DAddYE** [comment]
+1 congrats! Awesome!

**Comment by goncalossilva** [comment]
Great balance between design and simplicity.

**Comment by tilsammans** [comment]
I like this one a lot; it's clear with lots of breathing room, font size is good, works great on low and high resolutions and stresses both team effort and Matz as apex contributor. Not really sure about the parralax effect, the idea is great but implementation a bit jittery, so that might need tweaking. over all very well done!

**Comment by jmbejar** [comment]
It looks so good! 
My thumbs up goes for this design :)

**Comment by nicinabox** [comment]
The thing that concerns me about this design is that it's designed for a lot of data that doesn't actually exist. Consider that a large majority of the contributors don't even have a headshot; how can we expect them to have a 30-50 word bio? Does the ruby committers site really need it's own 30 word intro block?

These are the major elements of this design, however, there is no content to be filled there, and it without it the design is anemic and stark.

**Comment by nesquena** [comment]
+1! I really the design and the lightweight nature of it. Thanks Fred!

**Comment by fredwu** [comment]
Thanks for the great feedback everyone! :-)

Indeed the parallax effect is a bit jittery, I hadn't had too much time tweaking it, but I will, or otherwise I'd just remove the effect entirely if it cannot be tweaked to a satisfactory outcome.

@nicinabox: I consulted with Aaron Patterson during the early drafting stage and he said he would get the bios sorted. Besides, I am sure a great community like Ruby's, we wouldn't have any trouble coming up with a few sentences for each committer. The reason behind having bio, is to make the minisite more useful. I know when I read the rails core page, I find the little blurb for each core member a delight to read. :)

**Pull request closed without merging**
