### PR TITLE
Ruby Committers!

### PR DESCRIPTION
**Pull request by mnutt**
Here's another Ruby Committers design.

Preview: http://rc-mnutt.heroku.com/

I seem to have lost track of time at the end, so it was coded in a hurry.  If you want me to clean it up, I can.

### CODE REVIEW

**Comment by xaviershay** [comment]
This one is clearly the best. I vote this one.

**Comment by joho** [comment]
wow! nice homage to _why

**Comment by mculp** [comment]
+1

**Comment by veganstraightedge** [comment]
+1

**Comment by cqr** [comment]
it's so beautiful

**Comment by sdsykes** [comment]
+1 for the most interesting design that doesn't show matz as a man eater

**Comment by mehowte** [comment]
+1

**Comment by brainopia** [comment]
This drawing style is clearly synonymous to ruby itself.
Definitely +1 from me

**Comment by tonchis** [comment]
Nice! very original, unique and playful. Just like Ruby.
+1

**Comment by cqr** [comment]
Would it be possible to +1 this more than once?

**Comment by tilsammans** [comment]
This one is brilliant, absolutely superb. Great hommage to _why, it's very humane, different like Ruby. The colors are very early 90s-era video game, married to the clean and sophisticated look of today. Very well done, definitely stands out from the crowd! +10 from me.

**Comment by khustochka** [comment]
the best

**Comment by flavorjones** [comment]
my hands-down favorite. really nice work, mike.

**Comment by daveyeu** [comment]
+1

**Comment by ktheory** [comment]
+1

**Comment by ghost** [comment]
+1 Very nice. The _why touch is perfect for this.

**Comment by talltyler** [comment]
+1

**Comment by drbrain** [comment]
+1

**Comment by cldwalker** [comment]
+1 for style

**Comment by nodanaonlyzuul** [comment]
Wonderful.
Consider my vote cast!

**Comment by pjjw** [comment]
+1 here.

**Comment by fhwang** [comment]
+1

**Comment by elubow** [comment]
+1

**Comment by rochefort** [comment]
+1

**Pull request merged**
