### PR TITLE
Design Entry

### PR DESCRIPTION
**Pull request by tristandunn**
Sending a pull request of [my current design](http://ruby-committers.heroku.com/) in case I forget.

### CODE REVIEW

**Comment by veganstraightedge** [comment]
+1

**Comment by gautamrege** [comment]
+1

**Comment by jimmycuadra** [comment]
Second favorite.

**Comment by chrisharper** [comment]
+1

**Comment by goncalossilva** [comment]
I like this proposal. It shows more information than others in the same amount of space.

**Comment by michaelminter** [comment]
+1

**Comment by ejc** [comment]
Really like the simplicity of this. +1

**Comment by maxim** [comment]
Clean, well structured, info at fingertips.

**Pull request closed without merging**
