### PR TITLE
New look of Ruby Committers

### PR DESCRIPTION
**Pull request by kossnocorp**
Screenshot: http://bit.ly/fzhKiV

### CODE REVIEW

**Comment by meonkeys** [comment]
I can't view the screenshot.

**Comment by kossnocorp** [comment]
Very strange, I checked it and everything is ok. btw unshorted link: http://dl.dropbox.com/u/788800/Screenshots/y1qg.png

**Comment by meonkeys** [comment]
Sorry, my bad, for some reason DNS lookups were failing for me for dl.dropbox.com. The UI looks great!

**Comment by kossnocorp** [comment]
Thanks!

**Comment by kossnocorp** [comment]
I pushed my submission to Heroku: http://rucom.heroku.com/

**Pull request closed without merging**
