### PR TITLE
Design entry

### PR DESCRIPTION
**Pull request by ksaa**
Hi,

Here's my entry. I tried to bring minimalistic Japanese feel to it (as you know Ruby is from Japan) :) It's lightweight and everything is text so, you can make the changes if you wish. 

Also the top which now says "Ruby, programmer's best friend" can be replaced with navigation if you at some point decide extend the site.

I deployed also to http://karrisaarinen.com/rubyc/ so its easy to view and share (the banner in the upper corner is not there to stay, and not included in the design or on this repo)

Screenshot http://dl.dropbox.com/u/8355/rubycommitters.png
## Best of luck with your site!

Karri Saarinen
http://karrisaarinen.com
http://twitter.com/karrisaarinen

Kisko Labs http://kiskolabs.com

### CODE REVIEW

**Comment by justinko** [comment]
My favorite by far!

**Comment by ksaa** [comment]
Thanks!

**Comment by brainopia** [comment]
Nice one, clearly has all information needed, plus the only one who thought of anchor links 
+1

**Comment by nikosalonen** [comment]
Simplicity makes things beautiful!
+1

**Pull request closed without merging**
