### PR TITLE
Design Entry

### PR DESCRIPTION
**Pull request by machida**
Entry to rubycommitters.org contest. Preview here http://rc-machida.heroku.com/

### CODE REVIEW

**Comment by hoverlover** [comment]
Nice entry!

**Comment by machida** [comment]
Thank you!

**Comment by slayyyyer** [comment]
my favorite :D

**Comment by komagata** [comment]
Like it!

**Comment by func09** [comment]
Like it!

**Comment by tsukasa-hoki** [comment]
Like it!

**Comment by okutsuji** [comment]
Like it!

**Comment by yoshuki** [comment]
Great work!

**Comment by 1126born** [comment]
Like it!

**Comment by milkcocoa** [comment]
Great work!

**Comment by rono23** [comment]
Like it!

**Comment by milligramme** [comment]
Like it!

**Comment by jimmycuadra** [comment]
No offense to the creator but this is my least favorite. The patterns and little frills are too garish and clash with each other.

**Comment by g000001** [comment]
sweet!

**Comment by ruedap** [comment]
Like it!

**Comment by slayyyyer** [comment]
jimmycuadra..i don't think you're in the place to criticize designs..

**Pull request closed without merging**
