### PR TITLE
Ruby Committers team site

### PR DESCRIPTION
**Pull request by crissmancd**
This was fun to play around with

### CODE REVIEW

**Comment by wanderingmatt** [comment]
I would look to compress the overall layout of this design, but have to give it a +1 for that fabulous intro card. Psychedelic, man!

**Comment by ejc** [comment]
Really like the idea behind this. Would love it if the retro/8-bit idea was carried through a little more, like pixelated avatars or something.

Great work!

**Comment by bobanj** [comment]
+1

**Comment by drbrain** [comment]
+1

**Pull request closed without merging**
