### PR TITLE
MATZILLA!

### PR DESCRIPTION
**Pull request by ejc**
My second entry. http://matzilla.heroku.com

### CODE REVIEW

**Comment by hoverlover** [comment]
So pimp.

**Comment by hexgnu** [comment]
ZOMG so awesome

**Comment by miyucy** [comment]
+1

**Comment by rkh** [comment]
+1

**Comment by wanderingmatt** [comment]
Super original. Amazing illustration work!

**Comment by goncalossilva** [comment]
Awesome illustration. Clear winner in the category of "making you smile".

**Comment by elcuervo** [comment]
+1

**Comment by bobanj** [comment]
+1

**Comment by ejc** [comment]
Thanks everyone. Matzilla and I appreciate the love.

**Comment by peterc** [comment]
+1 - I almost wanna start a campaign to get this one to win..

**Comment by cldwalker** [comment]
+1

**Pull request closed without merging**
