### PR TITLE
DONE APPLYING TLC IN UR CODEZ

### PR DESCRIPTION
**Pull request by wanderingmatt**
I'd recommend pulling only one photo down for each committer with this design. Had a blast working on this - hope you like it! Let me know if you want any tweaks made.

http://wandering-rc.heroku.com/

### CODE REVIEW

**Comment by veganstraightedge** [comment]
+1

**Comment by lcowell** [comment]
+2 I like that it's a simple design that presents the information well.

**Comment by cqr** [comment]
Hey veganstraightedge and lcowell you should upvote the issue in addition to your comment.

**Comment by zimbatm** [comment]
+1 but like in real life, don't attach anything if you don't have the photo

**Comment by ejc** [comment]
This is sweet. +1

**Comment by texel** [comment]
PLUS ONE INTERNET>

**Comment by diasjorge** [comment]
+1

**Comment by jmbejar** [comment]
I like this one! It's simple, elegant and the info is easily readable.

Just a thought, I feel like the title is too simple, maybe it needs to be more prominent in some way..

Amazing job!

**Comment by wanderingmatt** [comment]
@zimbatm Agreed. Thanks for the feedback!

@jmbejar Totally agree. I wasn't smart enough to add a header area like some of the others. I was simply trying to style the content Aaron provided. Would love to flesh that out a bit more.

**Pull request closed without merging**
